// This file is auto-generated by @hey-api/openapi-ts

export type ApproveDraftRequest = {
    mode: 'create' | 'edit';
    avatar_id?: (string | null);
    draft: AvatarDraft;
};

export type mode = 'create' | 'edit';

export type AssistantChatRequest = {
    mode: 'create' | 'edit';
    avatar_id?: (string | null);
    messages?: Array<ChatMessage>;
    draft?: AvatarDraft;
};

export type AssistantChatResponse = {
    message: string;
    draft: AvatarDraft;
};

export type AvatarDraft = {
    name?: string;
    description?: string;
    visual_prompt?: string;
    image_url?: (string | null);
    image_key?: (string | null);
};

export type AvatarPublic = {
    name: string;
    description?: (string | null);
    id: string;
    owner_id: string;
    image_url: string;
    created_at: string;
    updated_at: string;
};

export type AvatarsPublic = {
    data: Array<AvatarPublic>;
    count: number;
};

export type AvatarUpdate = {
    name?: (string | null);
    description?: (string | null);
};

export type Body_avatars_create_avatar = {
    name: string;
    description?: (string | null);
    image: string;
};

export type Body_avatars_replace_avatar_image = {
    image: string;
};

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type ChatMessage = {
    role: 'user' | 'assistant';
    content: string;
};

export type role = 'user' | 'assistant';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    full_name: string;
    is_verified?: boolean;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    full_name?: (string | null);
    id: string;
    created_at?: (string | null);
};

export type UserRegister = {
    email: string;
    password: string;
    full_name?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    full_name?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    full_name?: (string | null);
    email?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
    input?: unknown;
    ctx?: {
        [key: string]: unknown;
    };
};

export type AvatarAssistantChatData = {
    requestBody: AssistantChatRequest;
};

export type AvatarAssistantChatResponse = (AssistantChatResponse);

export type AvatarAssistantApproveData = {
    requestBody: ApproveDraftRequest;
};

export type AvatarAssistantApproveResponse = (AvatarPublic);

export type AvatarsReadAvatarsData = {
    limit?: number;
    skip?: number;
};

export type AvatarsReadAvatarsResponse = (AvatarsPublic);

export type AvatarsCreateAvatarData = {
    formData: Body_avatars_create_avatar;
};

export type AvatarsCreateAvatarResponse = (AvatarPublic);

export type AvatarsReadAvatarData = {
    id: string;
};

export type AvatarsReadAvatarResponse = (AvatarPublic);

export type AvatarsUpdateAvatarData = {
    id: string;
    requestBody: AvatarUpdate;
};

export type AvatarsUpdateAvatarResponse = (AvatarPublic);

export type AvatarsDeleteAvatarData = {
    id: string;
};

export type AvatarsDeleteAvatarResponse = (Message);

export type AvatarsReplaceAvatarImageData = {
    formData: Body_avatars_replace_avatar_image;
    id: string;
};

export type AvatarsReplaceAvatarImageResponse = (AvatarPublic);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: string;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: string;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: string;
};

export type UsersDeleteUserResponse = (Message);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);